# Generated by Django 4.0.3 on 2022-04-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField(unique=True)),
                ('num_events', models.IntegerField(blank=True, null=True)),
                ('num_student', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventtbl',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_email', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField(unique=True)),
                ('event_category', models.CharField(blank=True, max_length=30, null=True)),
                ('event_description', models.CharField(blank=True, max_length=255, null=True)),
                ('event_phone', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'eventtbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateEvent',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uni_id', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'private_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicEvent',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('superadmin_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'public_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rso',
            fields=[
                ('rso_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uni_id', models.IntegerField()),
                ('num_students', models.IntegerField(blank=True, null=True)),
                ('num_events', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RsoEvent',
            fields=[
                ('rso_id', models.IntegerField()),
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField(unique=True)),
            ],
            options={
                'db_table': 'rso_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('superadmin_id', models.IntegerField(unique=True)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'super_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('uni_id', models.IntegerField(primary_key=True, serialize=False)),
                ('uni_name', models.CharField(blank=True, max_length=30, null=True)),
                ('num_students', models.IntegerField(blank=True, null=True)),
                ('uni_description', models.CharField(blank=True, max_length=200, null=True)),
                ('uni_location', models.CharField(blank=True, max_length=50, null=True)),
                ('gallery', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'university',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usertbl',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_password', models.IntegerField()),
                ('uni_id', models.IntegerField(blank=True, null=True)),
                ('rso_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usertbl',
                'managed': False,
            },
        ),
    ]
